=== Roy-Rebuffo/ejerciciosXML_XSD/ej_18_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="datosContactoBase">
        <xs:sequence>
            <xs:element name="datosContacto">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre"/>
                        <xs:element name="email"/>
                        <xs:element name="telefono">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\+[0-9]{1}-[0-9]{3}-[0-9]{4}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleado">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="datosContactoBase">
                                <xs:sequence>
                                    <xs:element name="departamento" type="xs:string" />
                                </xs:sequence>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cliente">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="datosContactoBase">
                                <xs:sequence>
                                    <xs:element name="historial_compras"></xs:element>
                                </xs:sequence>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Roy-Rebuffo/ejerciciosXML_XSD/EJ_18_XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej_18_XSD.xsd">
    <empleado>
        <datosContacto>
            <nombre>Juan Pérez</nombre>
            <email>juan@example.com</email>
            <telefono>+1-555-1234</telefono>
        </datosContacto>
        <departamento>IT</departamento>
    </empleado>
    <cliente>
        <datosContacto>
            <nombre>María Gómez</nombre>
            <email>maria@example.com</email>
            <telefono>+1-555-5678</telefono>
        </datosContacto>
        <historial_compras>2023-01-15</historial_compras>
    </cliente>
</empresa>
