=== Roy-Rebuffo/ejerciciosXML_XSD/ej_10_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="COD-[0-9]{3}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nombre"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="categoria">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Electrónica" />
                                    <xs:enumeration value="Hogar" />
                                    <xs:enumeration value="Deportes" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Roy-Rebuffo/ejerciciosXML_XSD/ej_10_XSD.xml
<?xml version="1.0" encoding="UTF-8"?> 
<inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:noNamespaceSchemaLocation="ej_10_XSD.xsd"> 
  <producto categoria="Electrónica"> 
     <codigo>COD-001</codigo> 
     <nombre>Smartphone XYZ</nombre> 
  </producto> 
  <producto categoria="Hogar"> 
     <codigo>COD-002</codigo> 
     <nombre>Aspiradora</nombre> 
  </producto> 
  <producto categoria="Deportes"> 
     <codigo>COD-003</codigo> 
     <nombre>Zapatillas</nombre> 
  </producto> 
</inventario>
