=== Roy-Rebuffo/ejerciciosXML_XSD/ej_15_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="usuarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre"></xs:element>
                            <xs:element name="contrasena">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9]{6,12}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Roy-Rebuffo/ejerciciosXML_XSD/ej_15_XSD.xml
<?xml version="1.0" encoding="UTF-8"?> 
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej_15_XSD.xsd"> 
  <usuario> 
     <nombre>ana123</nombre> 
     <contrasena>Pass123!</contrasena> <!-- Inválido: incluye un símbolo --> 
  </usuario> 
  <usuario> 
     <nombre>juan</nombre> 
     <contrasena>abcde</contrasena> <!-- Inválido: menos de 6 caracteres --> 
  </usuario> 
  <usuario> 
     <nombre>maria</nombre> 
     <contrasena>SecurePass1234</contrasena> <!-- Inválido: más de 12 caracteres --> 
  </usuario> 
  <usuario> 
     <nombre>carlos</nombre> 
     <contrasena>clave1234</contrasena> <!-- Válido --> 
  </usuario> 
</usuarios>
