=== Roy-Rebuffo/ejerciciosXML_XSD/ej_17_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- REUTILIZABLE -->
    <xs:complexType name="fechasBase">
        <xs:sequence>
            <xs:element name="fecha_nacimiento">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="fecha_registro">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- CODIGO USANDO REUTILIZABLE -->
    <xs:element name="usuarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="fechasBase">
                                <xs:sequence>
                                    <xs:element name="nombre"></xs:element>
                                </xs:sequence>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Roy-Rebuffo/ejerciciosXML_XSD/ej_17_XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej_17_XSD.xsd">


    <usuario>
        <fecha_nacimiento>1990-05-22</fecha_nacimiento>
        <fecha_registro>2023-08-15</fecha_registro>
        <nombre>Juan Pérez</nombre>
    </usuario>


    <usuario>
        <fecha_nacimiento>1985-11-03</fecha_nacimiento>
        <fecha_registro>2022-06-10</fecha_registro>
        <nombre>Ana Gómez</nombre>
    </usuario>


</usuarios>
