=== Roy-Rebuffo/ejerciciosXML_XSD/ej_24_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="libroTipo" mixed="true">
        <xs:sequence>
            <xs:element name="titulo" type="xs:string"></xs:element>
            <xs:element name="autor" type="xs:string"></xs:element>
            <xs:element name="año" type="xs:int"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" type="libroTipo" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Roy-Rebuffo/ejerciciosXML_XSD/ej_24_XSD.xml
<?xml version="1.0" encoding="UTF-8"?> 
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej_24_XSD.xsd">
 <libro> 
   <titulo>El Principito</titulo> 
   <autor>Antoine de Saint-Exupéry</autor> 
   Un clásico de la literatura infantil. 
   <año>1943</año> 
 </libro> 
 <libro> 
   <titulo>Cien años de soledad</titulo> 
   <autor>Gabriel García Márquez</autor> 
   Novela maestra del realismo mágico. 
   <año>1967</año> 
 </libro> 
</libros>
