=== Roy-Rebuffo/ejerciciosXML_XSD/ej_9_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="productos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="categoria_producto">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Electrónica"></xs:enumeration>
                                        <xs:enumeration value="Ropa"></xs:enumeration>
                                        <xs:enumeration value="Libros"></xs:enumeration>
                                        <xs:enumeration value="Hogar"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Roy-Rebuffo/ejerciciosXML_XSD/ej_9_XSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej_9_XSD.xsd">
    <producto>
        <categoria_producto>Electrónica</categoria_producto>
    </producto>
    <producto>
        <categoria_producto>Ropa</categoria_producto>
    </producto>
    <producto>
        <categoria_producto>Libros</categoria_producto>
    </producto>
    <producto>
        <categoria_producto>Hogar</categoria_producto>
    </producto>
</productos>
